### ISSUE TITLE
Organisation Logo

### ISSUE THREAD

**Issue by shapley** [gisquick/gisquick#153]
Replace 'GISQUICK' logo with a users logo at bottom of map.

**Comment by marcel-dancak** [comment]
Changing the logo at this particular place would not be that difficult. It would be much harder to replace all Gisquick logo images, like in the login form, intro page, settings...

We will definitely consider this or similar customizations, but they will be most likely available only in the more advanced hosting plans, which we would like to offer. But first we need to get to this stage.

**Comment by shapley** [comment]
Thanks...

**Comment by marcel-dancak** [comment]
Support for app customization per project was implemented. Right now it's also enabled on demo server, so if you want to try it, follow this [information](https://github.com/gisquick/gisquick/blob/master/clients/gisquick-web/ProjectCustomization.md) 

You can also see [live example](https://demo.gisquick.org/?PROJECT=gisquick/edit-demo)
