### ISSUE TITLE
Access publish metadata?

### ISSUE THREAD

**Issue by AndreasL-GL** [gisquick/gisquick#156]
Hey how would I go about accessing and changing publication metadata programmatically (Project > Update > Show gisquick metadata)?
I can't find it in the data/publish folder so my guess is that it's hidden somewhere in the docker-container. Or is it just query data and not available after saving?

The end goal is to be able to schedule updates of the maps and add / remove map markers based on availability from a geolocation-api. 
(From a python-script)

**Comment by marcel-dancak** [comment]
Internal Gisquick project files are still inside project directory, but now they are inside single hidden folder named `.gisquick`

Furthermore comparison to previous project structure, project information are stored in two main json files. One is `qgis.json`, which contains metadata generated by plugin from QGIS project file. Second is `settings.json`, and it this contains all Gisquick related settings.

**Comment by AndreasL-GL** [comment]
> Internal Gisquick project files are still inside project directory, but now they are inside single hidden folder named `.gisquick`
> 
> Furthermore comparison to previous project structure, project information are stored in two main json files. One is `qgis.json`, which contains metadata generated by plugin from QGIS project file. Second is `settings.json`, and it this contains all Gisquick related settings.

Hi I was able to create functionality to automatically generate the 3 other files(not quite done with qgis.json but looks simple enough) but i'm kind of stuck with project.json.

I may have missed something about qgis but I can't seem to be able to get the scale right and I don't even know where to begin with tile_resolutions?

How do you determine these values in gisquick?
Thanks again.
